version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: harmonix-frontend
    restart: unless-stopped
    networks:
      - harmonix-net
    environment:
      - NODE_ENV=production
      - PORT=3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: harmonix-backend
    restart: unless-stopped
    networks:
      - harmonix-net
    # ПЕРЕДАЄМО ВЕСЬ ФАЙЛ .env ОДРАЗУ В КОНТЕЙНЕР
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: harmonix-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - harmonix-net

networks:
  harmonix-net:
    driver: bridge
